# Generated by Django 3.2.9 on 2021-12-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('fileurl', models.CharField(max_length=1024)),
                ('size', models.CharField(max_length=20)),
                ('width', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('uploaddate', models.TimeField()),
                ('deleteurl', models.CharField(max_length=1024)),
            ],
            options={
                'ordering': ('-uploaddate',),
            },
        ),
    ]
