# Generated by Django 3.2.9 on 2022-01-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsmanage', '0002_imagelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelist',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
