# Generated by Django 3.2.9 on 2022-01-02 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsmanage', '0003_alter_imagelist_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelist',
            name='uploaddate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
