# Generated by Django 3.2.9 on 2022-01-02 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smmsmanage', '0004_alter_imagelist_uploaddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelist',
            name='uploaddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
