[loggers]
keys=root,basiclogger,smmslogger

[handlers]
keys=basicHanler,consoleHandler,smmsHanler

[formatters]
keys=basicFormatter

[logger_root]
level=ERROR
handlers=consoleHandler

[logger_basiclogger]
level=INFO
handlers=basicHanler
qualname=basiclogger
propagate=0

[logger_smmslogger]
level=INFO
handlers=smmsHanler
qualname=smmslogger
propagate=0

[handler_consoleHandler]
class=StreamHandler
args=(sys.stdout,)
level=DEBUG
formatter=basicFormatter

[handler_basicHanler]
class=handlers.TimedRotatingFileHandler
args=('../logs/basic.log', 'D', 1, 7)
level=INFO
formatter=basicFormatter

[handler_smmsHanler]
class=handlers.TimedRotatingFileHandler
args=('../logs/smms.log', 'D', 1, 30)
level=INFO
formatter=basicFormatter

[formatter_basicFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=%Y-%m-%d %H:%M:%S
