# Generated by Django 3.2.9 on 2021-12-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20211230_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='disk_usage_raw',
            field=models.IntegerField(null=True),
        ),
    ]
