# Generated by Django 3.2.9 on 2021-12-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_usage_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usage_percent',
            field=models.FloatField(null=True),
        ),
    ]
